# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_app/model.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc_app/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14grpc_app/model.proto\x12\x05model\"\xbe\x01\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12?\n\x0fml_model_params\x18\x02 \x03(\x0b\x32&.model.TrainRequest.MlModelParamsEntry\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x15\n\rtarget_column\x18\x04 \x01(\t\x1a\x34\n\x12MlModelParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x0ePredictRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x15\n\rtarget_column\x18\x03 \x01(\t\"\xac\x01\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\x12\x0e\n\x06y_true\x18\x02 \x03(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x02\x12\x1d\n\x15\x63lassification_report\x18\x04 \x01(\t\x12\x18\n\x10\x63onfusion_matrix\x18\x05 \x03(\x05\x12\x0b\n\x03\x66pr\x18\x06 \x03(\x02\x12\x0b\n\x03tpr\x18\x07 \x03(\x02\x12\x0f\n\x07roc_auc\x18\x08 \x01(\x02\x32\x86\x01\n\x0cModelService\x12\x37\n\nTrainModel\x12\x13.model.TrainRequest\x1a\x14.model.TrainResponse\x12=\n\x0cPredictModel\x12\x15.model.PredictRequest\x1a\x16.model.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_app.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_MLMODELPARAMSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_MLMODELPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=32
  _globals['_TRAINREQUEST']._serialized_end=222
  _globals['_TRAINREQUEST_MLMODELPARAMSENTRY']._serialized_start=170
  _globals['_TRAINREQUEST_MLMODELPARAMSENTRY']._serialized_end=222
  _globals['_TRAINRESPONSE']._serialized_start=224
  _globals['_TRAINRESPONSE']._serialized_end=272
  _globals['_PREDICTREQUEST']._serialized_start=274
  _globals['_PREDICTREQUEST']._serialized_end=347
  _globals['_PREDICTRESPONSE']._serialized_start=350
  _globals['_PREDICTRESPONSE']._serialized_end=522
  _globals['_MODELSERVICE']._serialized_start=525
  _globals['_MODELSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
